name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: install sqlite3
      run: sudo apt-get install sqlite3
    - name: install libsqlite3-dev
      run: sudo apt-get install libsqlite3-dev 
    - name: cmake
      run: cmake .
    - name: make all targets
      run: make all

    - name: UT for BtsApplication
      run: make BtsApplicationUT 

    - name: run BTS ut
      run: ./BTS/Tests/Application/BtsApplicationUT

    - name: UT for COMMON
      run: make COMMON_UT

    - name: UT for UeApplication
      run: make UeApplicationUT

    - name: UT for COMMON
      run: ./COMMON/Tests/COMMON_UT

    - name: UT for UE
      run: ./UE/Tests/Application/UeApplicationUT
